#!/bin/bash

# Launch the system tray
#
# Sadly one has to play around with the width, height, and specify the monitor
# in which the tray should be displayed.
trayer --edge top --align right --SetDockType true --SetPartialStrut true \
      --expand true --width 10 --transparent true --tint 0x5f5f5f --height 35 --monitor 1 &

# nm-tray &

workrave &

xscreensaver -no-splash &

xfce4-power-manager &

# To set the wallpaper use 'feh', e.g.:
#
#  feh --bg-fill --no-fehbg ~/.wallpapers/haskell-red-noise.png

# Change monitor layout
xrandr --output eDP-1  --off \
       --output DP-1   --off \
       --output DP-2   --off \
       --output DP-2-3 --off \
       --output DP-2-1 --mode 3840x2160 --rate 30 --pos 2560x0 --rotate normal \
       --output DP-2-2 --mode 2560x1440 --pos 0x0 --rotate normal

# Run the gnome-keyring-daemon to avoid issues you otherwise may encounter
# when using programs which expect access to the keyring.
eval $(gnome-keyring-daemon --start)

# Change the default X cursor away from the "X"
xsetroot -cursor_name left_ptr

# Trick to avoid recompilation on every startup. See
# https://github.com/xmonad/xmonad/blob/master/INSTALL.md#tell-xmonad-how-to-recompile-itself
exec $HOME/.local/bin/xmonad
